# Entrega 1 | Álgebra Linear, Vetores e Geometria Analítica
**Disciplina:** Álgebra Linear  
**Tema:** Representação de Dados de Pedidos em Matrizes e Operações Lineares  


## Introdução
Neste relatório utilizamos dados reais de pedidos (arquivo `Order_semicolon.csv`) provenientes do kit de dados fornecido pela Cannoli. Utilizaremos apenas o arquivo de pedidos pois ele já nos traz colunas numéricas contínuas, ideais para representar diretamente como vetores e matrizes, aplicando operaçoes de álgebra linear.

Cada pedido possui atributos como:

- **totalAmount**: valor total do pedido (R$)  
- **preparationTime**: tempo de preparo (minutos)  
- **takeOutTimeInSeconds**: tempo de retirada (segundos)  

Cada linha será representada como um **vetor**, e o conjunto dos pedidos formará uma **matriz**.  
Com isso, aplicamos operações de Álgebra Linear (transposição, soma de vetores e multiplicação de matrizes).

### 1. Importação e visualização dos dados

In [1]:
import pandas as pd
import numpy as np

# Ler os dados de pedidos
df_orders = pd.read_csv("Order_semicolon.csv", sep=";")

print("Primeiras linhas do arquivo de pedidos:")
display(df_orders.head())

Primeiras linhas do arquivo de pedidos:


id   companyId containerId         createdAt  customer displayId engineId  \
0   1  I0VP1DZXGU    AKVXT2FH  08/01/2025 15:47       525    O8CC98   E3R037   
1   2  04MEUULZ6W    KKMY5TG5  03/11/2024 22:30       694    HJ99VA   EJVOBV   
2   3  W2ZZS7CCZW    I87JLGTV  09/09/2024 05:49       491    XJJDH2   UDX1ZF   
3   4  SQ5MBL8L24    W3ZXOQHO  22/05/2025 06:22       846    J8QDM3   30FLOC   
4   5  0RCNJ6BRJD    NA0C0FOS  22/02/2025 01:23        77    H4LV73   QI3URN   

    engineName engineType                                     extraInfo  ...  \
0  DirectOrder        POS  Adipisci maiores nam eius vero nesciunt sed.  ...   
1  DirectOrder        APP                                           NaN  ...   
2       KDSPro        POS                                           NaN  ...   
3       KDSPro        WEB                Autem mollitia voluptas quasi.  ...   
4       KDSPro        POS                                           NaN  ...   

   orderTiming  orderType  salesChannel       scheduledAt      status  \
0    IMMEDIATE   DELIVERY       ANOTAAI               NaN  DISPATCHED   
1    IMMEDIATE   DELIVERY      WHATSAPP               NaN   CONCLUDED   
2    IMMEDIATE     INDOOR       EPADOCA               NaN   CONCLUDED   
3    SCHEDULED    TAKEOUT        99FOOD  22/05/2025 14:22    CANCELED   
4    SCHEDULED   DELIVERY        99FOOD  24/02/2025 11:23  DISPATCHED   

  preparationTime takeOutTimeInSeconds totalAmount         updatedAt  version  
0              45                 2131       90.91  09/01/2025 03:32   v3.7.8  
1              33                  374       99.69  04/11/2024 03:05   v2.3.0  
2              22                  247       45.97  09/09/2024 09:32   v1.9.5  
3              35                 1766      104.31  22/05/2025 21:39   v2.8.5  
4              20                 1219      105.50  22/02/2025 13:53   v2.1.3  

[5 rows x 23 columns]

### 2. Seleção de colunas para formar a matriz

In [ ]:
# Selecionar colunas de interesse
colunas_interesse = ["totalAmount", "preparationTime", "takeOutTimeInSeconds"]
colunas_existentes = [col for col in colunas_interesse if col in df_orders.columns]

print("\nColunas utilizadas para análise vetorial:", colunas_existentes)

# Criar matriz de dados com numpy
matriz_pedidos = df_orders[colunas_existentes].dropna().to_numpy()

print("\nMatriz de pedidos (NumPy array):")
print(matriz_pedidos)


Colunas utilizadas para análise vetorial: ['totalAmount', 'preparationTime', 'takeOutTimeInSeconds']

Matriz de pedidos (NumPy array):
[[  90.91   45.   2131.  ]
 [  99.69   33.    374.  ]
 [  45.97   22.    247.  ]
 ...
 [  66.56   23.   3162.  ]
 [  23.44   19.   2230.  ]
 [  30.13   78.   1861.  ]]


### 2.1. Representação em Vetores e Matrizes
Exemplo da matriz formada:

\[
\begin{bmatrix}
\text{totalAmount}_1 & \text{preparationTime}_1 & \text{takeOutTimeInSeconds}_1 \\
\text{totalAmount}_2 & \text{preparationTime}_2 & \text{takeOutTimeInSeconds}_2 \\
\vdots & \vdots & \vdots
\end{bmatrix}
\]

Cada linha representa um **pedido** (vetor).  
Cada coluna representa uma **característica** (atributo).

In [3]:
# Transposição da matriz
matriz_transposta = matriz_pedidos.T
print("\nMatriz Transposta:")
print(matriz_transposta)


Matriz Transposta:
[[  90.91   99.69   45.97 ...   66.56   23.44   30.13]
 [  45.     33.     22.   ...   23.     19.     78.  ]
 [2131.    374.    247.   ... 3162.   2230.   1861.  ]]


### 2.2. Transposição
A transposição troca linhas por colunas:

\[
\begin{bmatrix}
c_1 & c_2 & \cdots \\
c_3 & c_4 & \cdots \\
c_5 & c_6 & \cdots
\end{bmatrix}
\]

Assim conseguimos analisar **características** em vez de **pedidos**.

In [4]:
# Soma de vetores (Pedido 1 + Pedido 2)
if matriz_pedidos.shape[0] >= 2:
    soma_vetores = matriz_pedidos[0] + matriz_pedidos[1]
    print("\nSoma do Pedido 1 e Pedido 2:")
    print(soma_vetores)


Soma do Pedido 1 e Pedido 2:
[ 190.6   78.  2505. ]


### 3. Multiplicação de Matrizes
Definimos uma matriz de pesos:

\[
W =
\begin{bmatrix}
0.5 & 0.3 & 0.2 \\
0.2 & 0.5 & 0.3
\end{bmatrix}
\]

O resultado representa dois "modelos" diferentes avaliando os pedidos.

In [ ]:
# Multiplicação de matrizes (pesos x dados)
pesos = np.array([
    [0.5, 0.3, 0.2],  
    [0.2, 0.5, 0.3]  
])

resultado = np.dot(pesos, matriz_pedidos.T)
print("\nMultiplicação de matrizes (pesos x pedidos.T):")
print(resultado)


Multiplicação de matrizes (pesos x pedidos.T):
[[485.155 134.545  78.985 ... 672.58  463.42  410.665]
 [679.982 148.638  94.294 ... 973.412 683.188 603.326]]


## Conclusão
Neste relatório, representamos dados de pedidos em forma de **matriz** e aplicamos operações 
fundamentais da Álgebra Linear:

- **Transposição** → troca linhas por colunas.  
- **Soma de vetores** → combina características de diferentes pedidos.  
- **Multiplicação de matrizes** → aplica pesos diferentes às variáveis.  

Essas operações são a base de técnicas em **Inteligência Artificial** e **Aprendizado de Máquina**, 
mostrando como dados do mundo real podem ser manipulados matematicamente para gerar conhecimento.